### ISSUE TITLE
Western Windows1252 detected as SJIS

### ISSUE THREAD

**Issue by JSteunou** [polygonplanet/encoding.js#12]
title is self explanatory :) 

had the case with a little 4 lines extracted from Excel as CSV from a Windows computer

**Comment by JSteunou** [comment]
And with an example 

```
Prénom;Nom;Email
invitéàçù01;invite01;test011&@barcom
invite02;invitéàçù01;test021bar.com
;;testéç@bar.com
invitéàçù01;invite01;test99@barcom
```

You can save this text as Windows1252 with sublime or VSCode to reproduce the issue

**Comment by polygonplanet** [comment]
I tested your text in Sublime text, and my result was same as yours.
But sorry, encoding.js is not supported Windows1252 now because this library is for [Japanese encodings and Unicode](https://github.com/polygonplanet/encoding.js#available-encodings).
