### ISSUE TITLE
Vue3に対応してますか？

### ISSUE THREAD

**Issue by tarao96** [polygonplanet/encoding.js#39]
Vue3を使ったプロジェクトで使わせてもらっています。
UNICODEからSJISへの変換がうまくいかず、なぜかASCIIに変換されてしまっています。
もしかしたらVue3に対応していないのかと思い、issue投げさせてもらいました。

コード例
```
// composables/useFileControl.js
import Encoding from "encoding-japanese";

let unicodeArray = Encoding.stringToCode(csvData);
console.log(Encoding.detect(unicodeArray)); // UNICODE
let sjisArray = Encoding.convert(unicodeArray, "SJIS", "UNICODE");
console.log(Encoding.detect(sjisArray)); // ASCII
```

**Comment by polygonplanet** [comment]
@tarao96 
`csvData` はどんな文字列になりますか？
もし、SJISを文字列化してるようでしたら正しく扱えてないかもしれません。
> 文字コードの数値配列から文字列には [Encoding.codeToString](https://github.com/polygonplanet/encoding.js/blob/master/README_ja.md#%E9%85%8D%E5%88%97%E3%81%8B%E3%82%89%E6%96%87%E5%AD%97%E5%88%97%E3%81%AE%E7%9B%B8%E4%BA%92%E5%A4%89%E6%8F%9B-codetostringstringtocode) などのメソッドで変換できますが、JavaScript は上記の特徴があるため文字列化してしまうと文字コードによっては正しく扱えません。

参照：[README>各文字コードを文字列で扱うには？](https://github.com/polygonplanet/encoding.js/blob/master/README_ja.md#%E5%90%84%E6%96%87%E5%AD%97%E3%82%B3%E3%83%BC%E3%83%89%E3%82%92%E6%96%87%E5%AD%97%E5%88%97%E3%81%A7%E6%89%B1%E3%81%86%E3%81%AB%E3%81%AF)

また、detectの判定は確実ではなく絞り込みの結果になります。
対象がASCIIの範囲の場合、SJISとして変換してもASCIIとなります。

```js
const s = 'abc';
const sjis = Encoding.convert(s, { to: 'SJIS' });
Encoding.detect(sjis); // ASCII
```

> Vue3に対応

encoding.js は単体で動作するライブラリですので、vueなどのフレームワーク依存はなく動きます。

**Comment by tarao96** [comment]
@polygonplanet 
ご回答ありがとうございます。

> csvData はどんな文字列になりますか？
もし、SJISを文字列化してるようでしたら正しく扱えてないかもしれません。

サーバー側で文字列をSJISに変換しレスポンスした結果がcsvDataになるので、SJISの文字列になるはずです。
サーバー側でのSJIS変換処理を消したところ、うまく文字コード変換ができました。
ありがとうございます！

> また、detectの判定は確実ではなく絞り込みの結果になります。
対象がASCIIの範囲の場合、SJISとして変換してもASCIIとなります。

SJISとして変換してもASCIIとなる旨承知しました。

> encoding.js は単体で動作するライブラリですので、vueなどのフレームワーク依存はなく動きます。

Vueに依存せずに動作する旨承知しました。

**Comment by tarao96** [comment]
ご対応ありがとうございました。
CSVファイルの文字化けの問題は解決しました。
