### ISSUE TITLE
Suggestion: Add an "error" fallback option to Encoding.convert to fail loudly if unsupported characters are encountered

### ISSUE THREAD

**Issue by ojii** [polygonplanet/encoding.js#43]
We have a use-case where we have to check if a given string/content is valid ShiftJIS, currently we use this:

```js
function isShiftJISConvertible(s) {
  return Encoding.convert(Encoding.convert(s, "SJIS", "UNICODE"), "UNICODE", "SJIS") === s;
}
```

but that is wasteful since we encode twice. It would be nice if there was an option so we could do 

```js

function isShiftJISConvertible(s) {
  try {
    Encoding.convert(s, {from: "UNICODE", to: "SJIS", fallback: "error"})
    return true
  } catch {
    return false
  }
}
```

Would you accept a pull request to implement such a feature?

**Comment by polygonplanet** [comment]
@ojii 
encoding.js is primarily designed to simply ignore errors internally and avoid throwing unnecessary errors for most processes. But seeing the need for this feature, I plan to add a `fallback: error` option in the next release.

**Comment by polygonplanet** [comment]
@ojii 
I added this option in PR #44 . thanks for the issues!

**Comment by ojii** [comment]
thank you so much
