### ISSUE TITLE
decodeが一部の文字で出来ていない件

### ISSUE THREAD

**Issue by miyazakiyuuya** [polygonplanet/encoding.js#46]
治、鼠、蛇と翔の文字がうまくdecodeができていなかったです。

治が。に変換されていた。
翔が稍に変換されていた。

**Comment by miyazakiyuuya** [comment]
すいません解決しました。解決したやり方(2つ通り)
１のやり方
let xxxx = Encoding.conver(Encoding.stringToCode(input),'AUTO','SJIS');
let yyyy = Encoding.codeToString(Encoding.convert(xxx),'AUTO','UNICODE');

2のやり方
let xxxx = Encoding.conver(Encoding.stringToCode(input,'UNICODE'),'SJIS','UNICODE');
let yyyy = Encoding.codeToString(Encoding.convert(xxx,'UNICODE','SJIS');

**Comment by polygonplanet** [comment]
解決したようでよかったです。解決済みとしてcloseさせていただきますね

ただ、いただいたコードにはいくつか問題がありましたので、以下にメモしておきます。

> １のやり方
> let xxxx = Encoding.conver(Encoding.stringToCode(input),'AUTO','SJIS');
> let yyyy = Encoding.codeToString(Encoding.convert(xxx),'SJIS','UNICODE');
> 2のやり方
> let xxxx = Encoding.conver(Encoding.stringToCode(input,'UNICODE'),'SJIS','UNICODE');
> let yyyy = Encoding.codeToString(Encoding.convert(xxx,'UNICODE','SJIS'));

* `Encoding.convert(data, to, from)` は第二引数 `to` と第三引数 `from` に有効な文字コード名を指定する必要があります（`to` に `AUTO` の指定はできません）
* `codeToString` と `stringToCode` は引数を一つのみ受け取ることができます
* `Encoding.conver` は `convert` のtypoと思われます

正しいパラメータの使用方法については [Encoding.convert のAPIドキュメント](https://github.com/polygonplanet/encoding.js/blob/master/README_ja.md#encodingconvert-data-to-from) をご参照ください。

また、以下のテストコードで「治、鼠、蛇」の文字の変換を確認しましたが、問題は発生しませんでした。APIの指定に関することや、環境依存の問題でないかも併せてご確認ください。

```tsx
const data = Encoding.stringToCode('治、鼠、蛇');
['SJIS', 'EUCJP', 'JIS', 'UTF8', 'UTF16', 'UNICODE'].forEach((encodingName) => {
  const encoded = Encoding.convert(data, { to: encodingName, from: 'UNICODE' });
  const decoded = Encoding.convert(encoded, { to: 'UNICODE', from: encodingName });
  assert.deepStrictEqual(data, decoded);
  console.log(`Encoding: ${encodingName}, Decoded: ${Encoding.codeToString(decoded)}`);
});
// Encoding: SJIS, Decoded: 治、鼠、蛇
// Encoding: EUCJP, Decoded: 治、鼠、蛇
// Encoding: JIS, Decoded: 治、鼠、蛇
// Encoding: UTF8, Decoded: 治、鼠、蛇
// Encoding: UTF16, Decoded: 治、鼠、蛇
// Encoding: UNICODE, Decoded: 治、鼠、蛇
```
