### ISSUE TITLE
Could not convert from SJIS to UTF-8

### ISSUE THREAD

**Issue by huynh-duc-mulodo** [polygonplanet/encoding.js#5]
When I used below codes, data was not converted correctly.　Output was not displayed as Japanese, but strange characters.
コンバートのため下記のソースコードを使ったが、出力のデータは日本語で表示せずに変な文字で表示ました。
「è¦³é³ Kå­,ç·,çå· Yå­,å¥³,」

```
console.log(originalText);
var inputArray = str2Array(originalText); //sjis
var outputArray = Encoding.convert(inputArray, 'UTF8', 'SJIS');
var result = Encoding.codeToString(outputArray);
console.log(result);

function str2Array(str) {
     var array = [],i,il=str.length;
     for(i=0;i<il;i++) array.push(str.charCodeAt(i));
     return array;
}
```

**Comment by huynh-duc-mulodo** [comment]
Actually, the method codeToString should not be used in this case. It seems to be used for 16bit-based converting

**Comment by polygonplanet** [comment]
What is originalText string?

**Comment by huynh-duc-mulodo** [comment]
hello, originalText is data was read from file which is in SJIS encode

**Comment by polygonplanet** [comment]
Maybe, I think that the character code you are looking for is "Unicode".
"Unicode" is JavaScript's encoding, "UTF-8" is not JavaScript internal encoding.

```javascript
var outputArray = Encoding.convert(inputArray, 'UNICODE', 'SJIS');
```

**Comment by huynh-duc-mulodo** [comment]
Actually I used `var outputArray = Encoding.convert(inputArray, 'UNICODE', 'SJIS');` already. But I need to convert to UTF8 because I'm importing data into Salesforce platform. So the way I fixed this problem is not to use `Encoding.codeToString`. Instead of that, I came up with using

**Comment by polygonplanet** [comment]
[Encoding.codeToString](https://github.com/polygonplanet/encoding.js/blob/master/encoding.js#L3220) uses `String.fromCharCode.apply(null, code)` internally. Just making sure not to cause an RangeError when it is a large string.

**Comment by huynh-duc-mulodo** [comment]
Thanks for your reminding me of potential problems. I should apply library's method with a little bit of change
```
function arrayToString(uintArray) {
            var encodedString = Encoding.codeToString(uintArray);
            var decodedString = decodeURIComponent(escape(encodedString));
            return decodedString;
        }
```
