### ISSUE TITLE
[Browserify] Cannot find module in v1.0.28

### ISSUE THREAD

**Issue by tanakaworld** [polygonplanet/encoding.js#8]
I got dependency errors in the latest version of this package [`1.0.28`](https://github.com/polygonplanet/encoding.js/releases/tag/1.0.28)
Could you please check it ? @polygonplanet 

## Node.js Environment
- node: `6.9.1`
- npm: `3.10.8`
- browserify: `^13.0.0`

## Errors

```
Error: Cannot find module './util'
Error: Cannot find module './encoding-table'
Error: Cannot find module './config' 
Error: Cannot find module './encoding-detect' 
Error: Cannot find module './utf8-to-jis-table'
Error: Cannot find module './utf8-to-jisx0212-table'
Error: Cannot find module './jis-to-utf8-table'
Error: Cannot find module './jisx0212-to-utf8-table'
Error: Cannot find module './encoding-convert' 
Error: Cannot find module './kana-case-table'
```

**Comment by polygonplanet** [comment]
I tried `npm install` and `npm run test` with node v6.9.1 and npm v3.10.8, all tests worked successfully.
encoding.js 1.0.28 used browserify [v15.2.0](https://github.com/polygonplanet/encoding.js/blob/master/package.json#L12) now, `browserify: ^13.0.0` version may not be correct.

**Comment by tanakaworld** [comment]
The test is successfully completed, but failed to build by browserify in encoding.js `1.0.28`.

I made [a sample project](https://github.com/tanakaworld/sandbox-encoding.js/commit/61200bf22cf3d1fbb0c3c2ea7b39aa55d6ae9fcb).
Successfully `npm run build` in the version `1.0.26`, but failed in the version `1.0.28` .

```
$ npm run build

> sandbox-encoding.js@1.0.0 build /Users/tanakaworld/ws/dev/repo/sandbox-encoding.js
> browserify ./src/index.js -o dist/index.js

Error: Cannot find module './encoding-table' from '/Users/tanakaworld/ws/dev/repo/sandbox-encoding.js/node_modules/encoding-japanese'
    at /Users/tanakaworld/ws/dev/repo/sandbox-encoding.js/node_modules/browser-resolve/node_modules/resolve/lib/async.js:55:21
    at load (/Users/tanakaworld/ws/dev/repo/sandbox-encoding.js/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/tanakaworld/ws/dev/repo/sandbox-encoding.js/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /Users/tanakaworld/ws/dev/repo/sandbox-encoding.js/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:123:15)
```

Thanks.

**Comment by polygonplanet** [comment]
Thanks, I confirmed the same errors, but I don't know yet what is the cause...

**Comment by polygonplanet** [comment]
The cause was [`src/index.js`](https://github.com/polygonplanet/encoding.js/pull/9/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R5), fixed.
Thanks!
